import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;

import 'package:dartz/dartz.dart' as dartz;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:opket/core/admin_env.dart';
import 'package:opket/core/constants/app_icons.dart';
import 'package:opket/core/di/sl.dart';
import 'package:opket/core/failure/failure.dart';
import 'package:opket/core/config/usecase.dart';
import 'package:opket/core/services/api_client_new.dart';
import 'package:opket/core/services/auth_storage.dart';
import 'package:opket/core/theme/colors.dart';
import 'package:opket/core/theme/spacing.dart';
import 'package:opket/core/widgets/app_card.dart';
import 'package:opket/feat/ride_booking/presentation/widgets/ride_booking_option_card.dart';
import 'package:opket/feat/ride_options/domain/entities/ride_option.dart';
import 'package:shared_preferences/shared_preferences.dart';

part 'domain/repo/ride_options_repo.dart';
part './domain/usecase/get_ride_options.dart';
part './presentation/cubit/ride_options_cubit.dart';
part './presentation/cubit/ride_options_state.dart';
part './data/ride_options_remote_datasource.dart';
part './data/get_ride_options_impl.dart';
part './presentation/ride_options.dart';
part './presentation/ride_options_instant.dart';
part 'services/ride_options_cache_service.dart';
part 'data/ride_options_local_datasource.dart';
part 'presentation/cubit/selected_ride_options_cubit.dart';
